package xyz.moyuyc.work3;

/**
 * Created by Yc on 2016/3/14 for myCompiler.
 */
public enum Type{
    IF,ELSE,WHILE,DO,GOTO,BREAK,CONTINUE,PUBLIC,PROTECTED,PRIVATE,DEFAULT,ABSTRACT,CLASS,ENUM,
    INTERFACE,STATIC,SWITCH,CASE,CHAR,BYTE,INT,LONG,BOOLEAN,CATCH,DOUBLE,EXTENDS,FALSE,TRUE,FINAL,FINALLY,
    FLOAT,FOR,IMPLEMENTS,IMPORT,INSTANCEOF,NATIVE,NEW,NULL,PACKAGE,RETURN,SHORT,SUPER,THIS,SYNCHRONIZED,
    THROW,THROWS,TRANSIENT,TRY,VOID,VOLATILE, IDEN,
    LBB,RBB,LSB,RSB,ASSIGN,SEMI,COMMA,LE,LT,GE,GT,OR,BITOR,MULTIPLY,PLUS,DIVIDE,MINUS,AND,BITAND,BITNOT,NOT,
    DBPLUS,PLUSE,DBMINUS,MINUSE,MULTIPLYE, EE, DIVIDEE
}
